import styles from "../about/about.module.css"
import React from 'react'

const About = () => {
  return (
    <div>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sed tempora cupiditate rem explicabo adipisci culpa minus corrupti quasi ipsam qui et doloribus placeat laudantium harum totam dicta quod omnis sequi cumque eveniet, quos vel! Accusantium totam sed iste dolores veniam labore incidunt perspiciatis ipsa reiciendis omnis a, sint mollitia odio magnam magni sit dignissimos, quas aspernatur eum, expedita id unde optio. Nesciunt, labore nulla. Possimus incidunt, voluptatibus inventore dignissimos laudantium eligendi nostrum? Esse a laudantium vel doloribus, necessitatibus inventore nostrum perferendis itaque sapiente nobis suscipit deleniti praesentium exercitationem aliquam illum iure commodi animi nemo harum nesciunt! Eum magni necessitatibus corrupti doloremque illum? Vitae, ipsam nobis perferendis, reprehenderit ad repellendus enim inventore dicta, tenetur id cumque. Molestias deserunt magni impedit eius enim dolorum magnam sit itaque, quidem ullam iusto minima id dicta pariatur, et excepturi animi nesciunt qui eos, consectetur quia distinctio eveniet amet aperiam. Rerum esse in, voluptates vero eligendi porro sit necessitatibus modi consectetur ad tenetur sequi ratione provident cum suscipit veritatis quaerat ab minima consequatur nisi quis dignissimos velit mollitia ipsum! Ex magni fugiat recusandae dicta architecto dolore quam eius voluptatem voluptatum! Numquam omnis corporis provident ipsam cum culpa quo ab, mollitia atque quaerat dolore sint et minus optio rem at id consequatur natus accusamus doloribus molestiae necessitatibus consectetur dicta quod. In at minima, quasi doloribus architecto adipisci magni. Numquam ab obcaecati recusandae velit minima porro dignissimos, at reiciendis quisquam error eum harum ut ipsum reprehenderit explicabo molestiae accusantium illo tempore, cumque ex voluptatibus? Minus dolores officiis adipisci soluta aliquid. Fuga minima hic doloribus magni impedit, incidunt ipsam veritatis blanditiis facilis, optio sequi libero ducimus. Aspernatur distinctio optio quam quis debitis? Reprehenderit eligendi quo non aspernatur quidem eos voluptatum, quod repellat, quia quas voluptas ducimus blanditiis commodi reiciendis vitae impedit. Quo dolore quisquam earum veritatis ex corporis cupiditate.</div>
  )
}

export default About