import style from "../dashboard/dashboard.module.css"
import React from 'react'

const Dashboard = () => {
  return (
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Illum dolorem unde nemo dolores cumque soluta neque laudantium nihil eum minus facilis quaerat ipsam, odit doloremque suscipit aperiam facere officia expedita ratione blanditiis? Sint provident debitis unde accusamus reprehenderit harum voluptatum aperiam qui beatae dolorem ullam labore iusto minus cumque, libero laudantium ab perferendis, modi ipsa ratione! Fugit, ullam, blanditiis sunt provident impedit, quo odit ex totam laboriosam esse beatae nesciunt. Facere labore omnis quisquam aliquid reprehenderit officiis sint! Soluta ratione et adipisci vitae, consequuntur amet suscipit? Deserunt repellendus delectus hic aliquid! Nobis eveniet eum rerum harum necessitatibus reiciendis doloremque, deserunt doloribus est saepe, illo voluptates tempore magnam debitis? Aut rem illo delectus vero quis rerum esse, id libero tempore commodi, a adipisci, voluptas aliquid sapiente ipsa asperiores voluptate accusamus quisquam ut neque et dolore! Saepe provident accusamus quas corporis optio deserunt laudantium veniam temporibus ullam. Tenetur explicabo ullam quae itaque nisi. Veritatis, maiores. Quo hic iste ea repellendus repellat dicta est, quidem numquam? Aliquam repellat fugit laboriosam inventore! Eligendi iusto, unde ipsum aliquam, necessitatibus quisquam quaerat voluptatibus, nesciunt hic incidunt quas odit exercitationem cum! Porro, amet? Eaque voluptatem temporibus maiores, eius nam odio fugiat numquam velit quis, libero incidunt voluptate tenetur dolorum dicta dignissimos, nihil ipsa? Est iusto expedita asperiores ipsa praesentium iure! Dolorem doloremque temporibus porro? Illum explicabo fuga obcaecati unde sint dolores animi facere ex rem, optio veniam odit! Quae impedit dignissimos iste voluptatibus iure, sint sequi placeat labore accusantium eos esse est modi corporis neque obcaecati nemo aperiam eligendi error? Non delectus, in id sed facilis similique cumque veritatis debitis rerum molestias a hic dolore tempora voluptate? Enim praesentium, ea assumenda eveniet temporibus maiores reiciendis repellat non quod esse itaque quaerat possimus impedit culpa qui deleniti veniam quidem explicabo atque neque doloremque vero veritatis tenetur pariatur? Excepturi.</div>
  )
}

export default Dashboard