import styles from "../product/product.module.css"
import React from 'react'

const Product = () => {
  return (
    <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit quod, inventore, pariatur aliquid natus unde consequatur laudantium, ullam error numquam tenetur. Illo maxime facilis ullam adipisci! Eveniet repellat maxime modi numquam laboriosam quos voluptatem, quod, animi eos doloribus in nihil, eligendi rerum dolorum aliquid at illum repudiandae non praesentium cumque sequi deleniti dolore! Quam sed excepturi corrupti quia tempore, voluptatibus possimus sit dolor asperiores repellendus quae pariatur! Quam, ipsum beatae! Eius eos aliquid alias natus ab neque, doloremque corporis magnam explicabo nisi impedit, incidunt tenetur consectetur dolor ipsa sint mollitia harum aspernatur nam dolore pariatur at? Perferendis, aspernatur cumque? Beatae similique ratione, dicta provident veritatis perspiciatis odio pariatur sint. Aut provident quia dolore commodi possimus nesciunt, temporibus laborum assumenda dolores dolorum suscipit ut cum! Amet quam rem repellendus neque laborum voluptatibus optio quisquam dicta aperiam, accusantium quis minus deserunt fugiat exercitationem illum doloremque veritatis iste voluptatum! Voluptatibus eaque tempore facere assumenda reiciendis placeat, culpa iste omnis, ducimus molestias repudiandae quos impedit odio veritatis ipsum quae animi rem voluptate similique dicta odit expedita perferendis! Modi accusamus ad quisquam sit esse perferendis mollitia a repellendus! Et beatae tempora provident sequi quis. Perspiciatis ullam magnam atque cupiditate minima, animi sit. Atque voluptatem odio quis minus explicabo? Recusandae dolorum voluptatem laborum, exercitationem hic quod cupiditate provident officiis omnis ipsa praesentium mollitia incidunt architecto, necessitatibus accusamus officia perspiciatis facilis est animi laudantium nihil dicta et quasi accusantium? Nesciunt, maxime reprehenderit vel asperiores, numquam officia aut libero aliquid quia molestias explicabo cupiditate ad deserunt debitis dolor quae distinctio aperiam consequatur cum laborum eligendi unde! Nobis, neque veritatis deleniti, hic quidem obcaecati perferendis, dolorem beatae exercitationem tenetur officia ullam quae. Nemo magni quam veritatis aliquam? Sequi, qui, ipsa eveniet nobis omnis placeat tempora et aliquid quam iste error, itaque eius quae ab voluptatibus blanditiis vitae officia inventore.</div>
  )
}

export default Product