import About from "./about/About.jsx"
import Apps from "./apps/Apps.jsx"
import Auth from "./auth/Auth.jsx"
import Contact from "./contact/Contact.jsx"
import Dashboard from "./dashboard/Dashboard.jsx"
import Doctor from "./doctor/Doctor.jsx"
import Home from "./home/Home.jsx"
import Product from "./product/Product.jsx"
import Services from "./services/Services.jsx"
import Testimonial from "./testimonial/Testimonial.jsx"
import Leading from "./leading/Leading.jsx"
import Dowloads from "./dowloads/Dowloads.jsx"
import CustomerSaying from "./customersSaying/CustomerSaying.jsx"
import Article from "./article/Article.jsx"
import Welcome from "./welcomeCenter/Welcome.jsx"
import Register from "./register/Register.jsx"
export {About,Apps,Auth,Contact,Dashboard,Doctor,Home,Product,Services,Testimonial,Leading,Dowloads,CustomerSaying,Article,Welcome,Register}